### ISSUE TITLE
some metabolicTasks_Essential Fail when running prepHumanModelForftINIT

### ISSUE THREAD

**Issue by yasamantaebi** [SysBioChalmers/Human-GEM#810] opened 2024-03-06 15:48 UTC
### Discussed in https://github.com/SysBioChalmers/Human-GEM/discussions/809

<div type='discussions-op-text'>

<sup>Originally posted by **yasamantaebi** March  6, 2024</sup>
I am trying to run ftINIT on the Human-Gem model. In prepData step, some essential tasks fail.Hence, it's not possible to run the next steps. I am using SCip solver for RAVEN because of the problem in reaching gurobi academic license. Here is the output of the prepHumanModelForftINIT function:
Step 1: Gene rules
Step 2: First simplification
Step 3: Check tasks (~10 min)
PASS: [ER] Aerobic rephosphorylation of ATP from glucose
PASS: [ER] Aerobic rephosphorylation of GTP
PASS: [ER] Aerobic rephosphorylation of CTP
PASS: [ER] Aerobic rephosphorylation of UTP
FAIL: [BS] ATP de novo synthesis
PASS: [BS] CTP de novo synthesis
FAIL: [BS] GTP de novo synthesis
PASS: [BS] UTP de novo synthesis
FAIL: [BS] dATP de novo synthesis
PASS: [BS] dCTP de novo synthesis
FAIL: [BS] dGTP de novo synthesis
PASS: [BS] dTTP de novo synthesis
PASS: [SU] Histidine uptake
PASS: [SU] Isoleucine uptake
PASS: [SU] Leucine uptake
PASS: [SU] Lysine uptake
PASS: [SU] Methionine uptake
PASS: [SU] Phenylalanine uptake
PASS: [SU] Threonine uptake
PASS: [SU] Tryptophan uptake
PASS: [SU] Valine uptake
PASS: [IC] Glycerate 3-phosphate  de novo synthesis
PASS: [IC] Mitochondrial acetyl-CoA de novo synthesis
PASS: [IC] Mitochondrial AKG de novo synthesis
PASS: [IC] Erythrose 4-phosphate de novo synthesis
PASS: [IC] Fructose 6-phosphate de novo synthesis
PASS: [IC] Glyceraldehyde 3-phosphate de novo synthesis
PASS: [IC] Glucose 6-phosphate de novo synthesis
PASS: [IC] Mitochondrial oxaloacetate de novo synthesis
PASS: [IC] Phosphoenolpyruvate de novo synthesis
PASS: [IC] Pyruvate de novo synthesis
PASS: [IC] Ribose 5-phosphate de novo synthesis
PASS: [IC] Mitochondrial succinyl-CoA de novo synthesis
PASS: [BS] Cholesterol de novo synthesis
PASS: [BS] Protein synthesis from AAs
PASS: [ER] Oxidative phosphorylation
PASS: [ER] Oxidative decarboxylation
PASS: [ER] Krebs cycle NADH
PASS: [ER] Ubiquinol-to-proton
PASS: [ER] Ubiquinol-to-ATP
PASS: [SU] Beta oxidation of saturated FA
FAIL: [SU] Beta oxidation of long-chain FA
PASS: [SU] Beta oxidation of odd-chain FA
PASS: [SU] Beta oxidation of unsaturated fatty acid (n-9) 
FAIL: [SU] Beta oxidation of unsaturated fatty acid (n-6) 
FAIL: [SU] Uptake and beta oxidation of all NEFAs
PASS: [SU] Choline uptake
PASS: [SU] Inositol uptake
FAIL: [BS] Phosphatidylcholine de novo synthesis
FAIL: [BS] Phosphatidylethanolamine de novo synthesis
FAIL: [BS] Phosphatidylserine de novo synthesis
FAIL: [BS] Phosphatidylinositol de novo synthesis
PASS: [BS] Thiamin phosphorylation to TPP
FAIL: [BS] Coenzyme A synthesis from pantothenate
FAIL: [BS] FAD synthesis from riboflavin
FAIL: [BS] Heme biosynthesis
FAIL: [GR] Growth on Ham's media (biomass production)
Step 4: Second simplification (~1 hour)
Starting parallel pool (parpool) using the 'local' profile ...
Connected to the parallel pool (number of workers: 4).
Analyzing and transferring files to the workers ...done.
Step 5: Final work
IdleTimeout has been reached.
Parallel pool using the 'local' profile is shutting down.</div>

**Comment by JHL-452b** [comment] 2024-03-19 10:35
Hi, I have tried using different solvers today to get prepData. I noticed that when using the gurobi solver, all tasks passed, but when using the glpk solver, 7 tasks(dTTP de novo synthesis, Protein synthesis from AAs, Ubiquinol-to-ATP, Beta oxidation of odd-chain FA, Beta oxidation of unsaturated fatty acid (n-9), Beta oxidation of unsaturated fatty acid (n-6) and Growth on Ham's media (biomass production)) failed. Combined with your result of using the SCIP solver (15 fail), I think it is caused by the solver. Since Human-GEM contains more than 10,000 reactions, there may be certain requirements on the performance of the solver, so I suggest you change the gurobi solver to run ftINIT.

**Comment by edkerk** [comment] 2024-03-19 23:49
As mentioned above, human-GEM is a large model, while ftINIT is a complex approach, so it indeed heavily depends on an well-functioning solver. Gurobi is superior in that aspect, so its use is highly recommended for these tasks.

I can however not replicate your observation, using `scip` here is [terribly slow](https://github.com/SysBioChalmers/RAVEN/wiki/Installation#solvers), but all the tasks pass.

Could you please report your RAVEN version; MATLAB version; and operating system version?

**Comment by feiranl** [comment] 2024-04-23 11:31
I am closing this issue since we don't get reply for one month. But feel free to reopen this if you still have this issue.

**Closed by feiranl** 2024-04-23 11:31 UTC
